#!/usr/bin/env bash
# theme-finder.sh - Search and compare color themes
# Usage: ./tools/theme-finder.sh search <query> | compare <theme> | popular | list

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PALETTE_FILE="$REPO_ROOT/palette.json"

# Colors for output
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Popular theme repositories for comparison
POPULAR_THEMES=(
  "catppuccin/catppuccin"
  "nordtheme/nord"
  "dracula/dracula-theme"
  "folke/tokyonight.nvim"
  "rose-pine/rose-pine"
  "dylanaraps/pywal"
  "elenapan/dotfiles"
  "base16-project/base16-schemes"
)

# Search GitHub for themes
search_themes() {
  local query="$1"
  echo -e "${CYAN}Searching for themes matching: $query${NC}\n"
  
  if command -v gh &>/dev/null; then
    gh search repos "$query theme" --limit 10 --json name,description,stargazers,url \
      --jq '.[] | "\(.name) - \(.description) (⭐ \(.stargazersCount))\n  \(.url)"'
  else
    echo "GitHub CLI (gh) not installed. Install with: sudo pacman -S github-cli"
    echo "Alternatively, search manually at: https://github.com/search?q=$query+theme"
  fi
}

# Compare Violet Void with another theme
compare_theme() {
  local theme="$1"
  echo -e "${PURPLE}Comparing Violet Void with $theme${NC}\n"
  
  if [[ ! -f "$PALETTE_FILE" ]]; then
    echo "Error: palette.json not found at $PALETTE_FILE"
    exit 1
  fi
  
  # Extract Violet Void colors
  local vv_background=$(jq -r '.backgrounds.primary' "$PALETTE_FILE" 2>/dev/null || echo "N/A")
  local vv_foreground=$(jq -r '.foregrounds.primary' "$PALETTE_FILE" 2>/dev/null || echo "N/A")
  local vv_accent=$(jq -r '.accents.base.cyan' "$PALETTE_FILE" 2>/dev/null || echo "N/A")
  
  echo -e "${GREEN}Violet Void Palette:${NC}"
  echo "  Background: $vv_background"
  echo "  Foreground: $vv_foreground"
  echo "  Accent (Cyan): $vv_accent"
  echo ""
  
  # Try to fetch theme colors from GitHub
  if command -v gh &>/dev/null; then
    echo -e "${YELLOW}Fetching $theme palette...${NC}"
    local repo_info=$(gh repo view "$theme" --json description,url 2>/dev/null || echo "Not found")
    
    if [[ -n "$repo_info" ]] && [[ "$repo_info" != "Not found" ]]; then
      echo "$repo_info" | jq -r '"\(.description)\n  \(.url)"' 2>/dev/null || echo "$repo_info"
      echo ""
      echo -e "${YELLOW}Note: Manual comparison required.${NC}"
      echo "1. Clone the repository"
      echo "2. Extract palette colors from theme files"
      echo "3. Use tools/color-name-lookup.sh to map colors"
    fi
  else
    echo "GitHub CLI (gh) required for theme comparison."
    echo "Install: sudo pacman -S github-cli"
  fi
  
  echo ""
  echo -e "${CYAN}Color Mapping Suggestions:${NC}"
  echo "  Violet Void → $theme"
  echo "  Background: $vv_background → [target background]"
  echo "  Foreground: $vv_foreground → [target foreground]"
  echo "  Accent: $vv_accent → [target accent]"
}

# List popular themes
list_popular() {
  echo -e "${PURPLE}Popular Theme Repositories:${NC}\n"
  
  for theme in "${POPULAR_THEMES[@]}"; do
    if command -v gh &>/dev/null; then
      local info=$(gh repo view "$theme" --json name,description,stargazers 2>/dev/null || echo "")
      if [[ -n "$info" ]]; then
        echo "$info" | jq -r '"• \(.name) - \(.description) (⭐ \(.stargazersCount))"' 2>/dev/null || echo "• $theme"
      else
        echo "• $theme"
      fi
    else
      echo "• $theme"
    fi
  done
  
  echo ""
  echo -e "${CYAN}Usage:${NC}"
  echo "  ./tools/theme-finder.sh compare catppuccin/catppuccin"
  echo "  ./tools/theme-finder.sh search 'dark purple'"
}

# Generate comparison report
generate_report() {
  local output="${1:-$REPO_ROOT/docs/theme-comparison.md}"
  echo -e "${GREEN}Generating theme comparison report...${NC}\n"
  
  mkdir -p "$(dirname "$output")"
  
  cat > "$output" << 'EOF'
# Theme Comparison Report

Generated by `tools/theme-finder.sh`

## Violet Void vs Popular Themes

This report compares the Violet Void color palette with popular theme palettes.

### Violet Void Characteristics

- **Background:** Deep purple (#1a1625)
- **Foreground:** Soft lavender (#e0d8f0)
- **Primary Accent:** Cyan (#61afef)
- **Secondary Accent:** Magenta (#c678dd)
- **Style:** Dark, low-contrast, purple-tinted

### Comparison Table

| Theme | Background | Foreground | Accent | Style |
|-------|------------|------------|--------|-------|
| Violet Void | #1a1625 | #e0d8f0 | #61afef | Dark Purple |
| Catppuccin Mocha | #1e1e2e | #cdd6f4 | #89b4fa | Dark Blue |
| Nord | #2e3440 | #d8dee9 | #88c0d0 | Dark Blue-Grey |
| Dracula | #282a36 | #f8f8f2 | #bd93f9 | Dark Purple |
| Tokyo Night | #1a1b26 | #c0caf5 | #7aa2f7 | Dark Blue |

### Migration Notes

When migrating from other themes:
1. Map background colors preserving contrast ratios
2. Map accent colors to closest hue matches
3. Verify WCAG contrast for text/background combinations
4. Test syntax highlighting in target applications

See `docs/comparisons/README.md` for detailed migration guides.
EOF
  
  echo -e "${GREEN}Report generated: $output${NC}"
}

# Main command router
main() {
  local command="${1:-list}"
  
  case "$command" in
    search)
      search_themes "${2:-dark purple}"
      ;;
    compare)
      compare_theme "${2:-catppuccin/catppuccin}"
      ;;
    popular|list)
      list_popular
      ;;
    report)
      generate_report "${2:-}"
      ;;
    *)
      echo "Usage: $0 {search <query>|compare <theme>|popular|report [output]}"
      echo ""
      echo "Commands:"
      echo "  search <query>  Search GitHub for themes"
      echo "  compare <theme> Compare Violet Void with another theme"
      echo "  popular         List popular theme repositories"
      echo "  report          Generate comparison report"
      exit 1
      ;;
  esac
}

main "$@"
